Another fix
There are 2 cases using `window` will crash:
1- ReferenceError: window is not defined
2- TypeError: window.setTimeout is not a function (or setInterval or clearTimeout or clearInterval)

So for instance if someone works around window is not defined by doing the following:
`global.window = {document: {createElementNS: () => {return {}} }};`

If we still don't catch this error, MainScheduler will break.

So this approach will ensure that if window fails, we will fallback to external functions which should map to nodeJs timer functions