Fix NodeJs: TypeError: window.setTimeout is not a function #485
- Added external functions `setTimeout`, `setInterval`, `clearTimeout`, and `clearInterval`
- Created a Timers object that will handle calls
- If window is defined then use the window functions else use the external functions